name: freyja-h3n2-pathogen
channels:
  - conda-forge
  - bioconda
dependencies:
  - augur
  - python=3.8
  - git
  - pip
  - nextflow
  - pip:
      - pandas==1.4.1
      - tqdm==4.64.0
      - biopython==1.79
      - >-
        -e
        git+https://github.com/jeetsukumaran/DendroPy.git@26c3bfba473ddee5db2856c79b7f22702ce903e1#egg=DendroPy
  - python=3.8
